### ISSUE TITLE
demo-topology for upb-emulator-mano-integration-demo

### ISSUE THREAD

**Issue by edmaas** [sonata-nfv/son-tutorials#10]
starting the demo-topology works, but it reports a lot of "[ErrNo 99] Cannot assign requested address".
Tested both on a local machine with no other sonata services running and on a machine running the sonata platform at the time.
To reproduce: "sudo python son-tutorials/upb-emulator-mano-integration-demo/demo_topology.py"

**Comment by mpeuster** [comment]
Reason seems to be that the current version of the demo topology hardcodes the IP of the interfaces to listen on:

```python
        api1 = OpenstackApiEndpoint("172.0.0.101", 6001)
        api2 = OpenstackApiEndpoint("172.0.0.101", 6002)
        api3 = OpenstackApiEndpoint("172.0.0.101", 6003)
        api4 = OpenstackApiEndpoint("172.0.0.101", 6004)
```

This works for the used demo VM, but must be changed to the public interface of the machine on which the topology is started or `127.0.0.1` (but you cannot access this from within another Docker containers e.g., running the IA). Using the IP of `docker0` of the host machine might also work well.
